name: Docker Build

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest ComfyUI commit hash
        id: comfyui_hash
        run: |
          COMFYUI_HASH=$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/commits/master | jq -r '.sha[:7]')
          echo "COMFYUI_HASH=$COMFYUI_HASH" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if version exists
        id: version_check
        run: |
          VERSION_EXISTS=$(curl -s -f https://ghcr.io/v2/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/manifests/${{ steps.comfyui_hash.outputs.COMFYUI_HASH }} > /dev/null 2>&1; echo $?)
          if [ "$VERSION_EXISTS" -eq 0 ]; then
            echo "VERSION_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: steps.version_check.outputs.VERSION_EXISTS == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/comfyui:latest
            ghcr.io/${{ env.OWNER_LC }}/comfyui:${{ steps.comfyui_hash.outputs.COMFYUI_HASH }}
