name: Docker Build

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest ComfyUI commit hash
        id: comfyui_hash
        run: |
          COMFYUI_HASH=$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/commits/master | jq -r '.sha[:7]')
          echo "COMFYUI_HASH=$COMFYUI_HASH" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-arch
        run: |
          sudo apt-get update && sudo apt-get install -y qemu binfmt-support qemu-user-static

      - name: Set up Docker Buildx
        id: buildx_setup
        run: |
          docker buildx create --use --name mybuilder
          echo "BUILDER_NAME=mybuilder" >> $GITHUB_ENV

      - name: Check if Docker version exists
        id: version_check
        env:
          IMAGE_NAME: ${{ env.OWNER_LC }}/comfyui
          IMAGE_TAG: ${{ steps.comfyui_hash.outputs.COMFYUI_HASH }}
        run: |
          TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          result=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TOKEN" https://ghcr.io/v2/${IMAGE_NAME}/manifests/${IMAGE_TAG})
          if [ $result -eq 200 ]; then
            echo "Image ${IMAGE_NAME}:${IMAGE_TAG} already exists"
            echo "VERSION_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "Image ${IMAGE_NAME}:${IMAGE_TAG} does not exist"
            echo "VERSION_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: steps.version_check.outputs.VERSION_EXISTS == 'false'
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          builder: ${{ env.BUILDER_NAME }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/comfyui:latest
            ghcr.io/${{ env.OWNER_LC }}/comfyui:${{ steps.comfyui_hash.outputs.COMFYUI_HASH }}
